import type { CompanyRecord, KnowledgeFinding, SourceDocument } from "@/lib/types";

const createdAt = "2026-01-15T09:00:00.000Z";
const actor = "user_super_admin";

function address(line1: string, city: string, state: string, postalCode: string, country: string) {
  return { line1, line2: "", city, state, postalCode, country };
}

function company(input: {
  id: string;
  legalName: string;
  displayName: string;
  companyType?: string;
  primaryContact: string;
  contactTitle?: string;
  email: string;
  phone?: string;
  website?: string;
  line1?: string;
  city: string;
  state: string;
  postalCode?: string;
  country: string;
  jurisdiction?: string;
  notes: string;
}): CompanyRecord {
  const addr = address(input.line1 ?? "", input.city, input.state, input.postalCode ?? "", input.country);
  return {
    id: input.id,
    legalName: input.legalName,
    displayName: input.displayName,
    companyType: input.companyType ?? "LLC",
    primaryContact: input.primaryContact,
    contactTitle: input.contactTitle ?? "",
    email: input.email,
    phone: input.phone ?? "",
    website: input.website ?? "",
    billingAddress: addr,
    businessAddress: addr,
    city: input.city,
    state: input.state,
    postalCode: input.postalCode ?? "",
    country: input.country,
    jurisdiction: input.jurisdiction ?? `${input.state}, ${input.country}`,
    relationshipStatus: "active",
    notes: input.notes,
    createdAt,
    updatedAt: createdAt,
    createdBy: actor,
  };
}

export const CLIENT_COMPANIES: CompanyRecord[] = [
  company({
    id: "co_prime_medical",
    legalName: "Prime Medical Outlet LLC",
    displayName: "Prime Medical Outlet",
    primaryContact: "Zaveen Tatari",
    email: "info@primedicaloutlet.com",
    line1: "1005 S Muskogee Ave",
    city: "Tahlequah",
    state: "OK",
    postalCode: "74464",
    country: "United States",
    notes: "Lead generation — Final Expense and DME. Agreement dated 20 Jun 2025.",
  }),
  company({
    id: "co_atleads",
    legalName: "Atleads LLC",
    displayName: "Atleads",
    primaryContact: "Anthony Ferlanti",
    contactTitle: "Contact",
    email: "anthony@atleads.com",
    website: "https://www.atleads.com",
    line1: "7777 Glades Rd",
    city: "Boca Raton",
    state: "FL",
    postalCode: "33434",
    country: "United States",
    notes: "Lead generation for affiliate offers. Agreement dated 3 Dec 2024.",
  }),
  company({
    id: "co_anchor_line",
    legalName: "Anchor Line Insurance",
    displayName: "Anchor Line Insurance",
    companyType: "Agency",
    primaryContact: "Anchor Line Insurance",
    email: "info@anchorlineinsurance.test",
    line1: "3423 Chiquita Blvd",
    city: "Cape Coral",
    state: "FL",
    postalCode: "33914",
    country: "United States",
    notes: "Collaboration — inbound auto insurance calls. Agreement dated 11 Jan 2026.",
  }),
  company({
    id: "co_launch_forward",
    legalName: "Launch Forward",
    displayName: "Launch Forward",
    companyType: "Affiliate",
    primaryContact: "Rocky Manrique",
    contactTitle: "Owner",
    email: "rocky@launchforward.test",
    city: "Columbus",
    state: "OH",
    country: "United States",
    notes: "Collaboration — MVA leads. Agreement dated 27 Mar 2025.",
  }),
  company({
    id: "co_rf_insurance",
    legalName: "RF Insurance Agency",
    displayName: "RF Insurance Agency",
    companyType: "Agency",
    primaryContact: "Renzo Figueroa",
    contactTitle: "Owner",
    email: "renzofigueroa1987@gmail.com",
    city: "",
    state: "",
    country: "United States",
    jurisdiction: "United States",
    notes: "Collaboration — insurance leads. Agreement dated 2 May 2025.",
  }),
  company({
    id: "co_poshnee",
    legalName: "Poshnee Tech (SMC-Private) Limited",
    displayName: "Poshnee Tech",
    companyType: "SMC-Private Limited",
    primaryContact: "Awais Anwer Khawaja",
    contactTitle: "Owner",
    email: "awais@poshnee.test",
    line1: "Office 1-12, Second Floor, Burj-e-Noor Trading Center, Shamsabad",
    city: "Rawalpindi",
    state: "Punjab",
    country: "Pakistan",
    jurisdiction: "Pakistan",
    notes: "Lead generation (Final Expense inbound) and media buying services. Agreements dated Jun 2025.",
  }),
  company({
    id: "co_all_star_bpo",
    legalName: "All Star BPO",
    displayName: "All Star BPO",
    companyType: "BPO",
    primaryContact: "Hamza Tariq",
    contactTitle: "Owner",
    email: "hamza@allstarbpo.test",
    line1: "Chandni Chowk Flyover, B-Block, Satellite Town",
    city: "Rawalpindi",
    state: "Punjab",
    postalCode: "43000",
    country: "Pakistan",
    jurisdiction: "Pakistan",
    notes: "Lead generation — Final Expense inbound calls. Agreement dated 14 Aug 2025.",
  }),
  company({
    id: "co_first_party_digital",
    legalName: "Influencer Interactive, LLC DBA First Party Digital",
    displayName: "First Party Digital",
    primaryContact: "Greg",
    email: "greg@firstpartydigital.com",
    line1: "627 Steamboat Rd, 2nd Floor",
    city: "Naperville",
    state: "IL",
    postalCode: "60565",
    country: "United States",
    notes: "Lead generation — workers' compensation claims. Agreement dated 2 May 2025.",
  }),
  company({
    id: "co_exclusive_media",
    legalName: "Exclusive Media Corporation",
    displayName: "Exclusive Media Corporation",
    companyType: "Corporation",
    primaryContact: "Thomas Varghese",
    contactTitle: "CEO",
    email: "thomas@exclusivemedia.test",
    line1: "7055 Old Katy Road, Suite 1019",
    city: "Houston",
    state: "TX",
    postalCode: "77024",
    country: "United States",
    notes: "Lead generation — exclusive MVA leads. Agreement dated 26 Nov 2025.",
  }),
  company({
    id: "co_capital_media",
    legalName: "Capital Media Agency",
    displayName: "Capital Media Agency",
    companyType: "Agency",
    primaryContact: "Debra",
    email: "debra@capitalmediaagency.com",
    line1: "5924 Aretha Place, Unit 203",
    city: "Virginia Beach",
    state: "VA",
    postalCode: "23455",
    country: "United States",
    notes: "Lead generation. Agreement dated 17 Jun 2025.",
  }),
  company({
    id: "co_hatim_abbasi",
    legalName: "Hatim Hameed Abbasi",
    displayName: "Hatim Hameed Abbasi",
    companyType: "Individual",
    primaryContact: "Hatim Hameed Abbasi",
    email: "hatimhameed704@gmail.com",
    phone: "+92 320 9558273",
    line1: "Village and Post Office Ausia, Tehsil & District Murree",
    city: "Murree",
    state: "Punjab",
    country: "Pakistan",
    jurisdiction: "Pakistan",
    notes: "Lead generation — auto insurance inbound calls. Agreement dated 25 Sep 2025.",
  }),
  company({
    id: "co_nettx",
    legalName: "Nettx Marketing",
    displayName: "Nettx Marketing",
    companyType: "Agency",
    primaryContact: "Tushar Raj",
    contactTitle: "CEO",
    email: "tushar.raj@nettxmarketingsolutions.com",
    city: "",
    state: "",
    country: "United States",
    jurisdiction: "United States",
    notes: "Lead generation — affiliate offers and MVA. Agreement dated 16 Jul 2025.",
  }),
  company({
    id: "co_zednex",
    legalName: "ZEDNEX PRIVATE LIMITED / ZEDNEX GLOBAL LLC",
    displayName: "Zednex",
    companyType: "Private Limited",
    primaryContact: "Syed Sahir Abbas",
    email: "sahir@zedbpo.com",
    phone: "+92 314 6062442",
    line1: "624-626 Eden Tower, Gulberg 3",
    city: "Lahore",
    state: "Punjab",
    country: "Pakistan",
    jurisdiction: "Pakistan",
    notes: "Medical billing lead generation. Agreement dated 30 Jul 2026.",
  }),
  company({
    id: "co_lone_star",
    legalName: "Lone Star Financial & Senior Services LLC",
    displayName: "Lone Star Financial",
    primaryContact: "Steve Baucom",
    email: "steve@lonestarfinancial.test",
    line1: "713 Edwards Walk Dr",
    city: "Cedar Park",
    state: "TX",
    postalCode: "78613",
    country: "United States",
    notes: "Collaboration — Medicare / Final Expense acquisition system. Agreement dated 2 May 2026.",
  }),
  company({
    id: "co_satellite_bpo",
    legalName: "Satellite BPO",
    displayName: "Satellite BPO",
    companyType: "BPO",
    primaryContact: "Saifullah Chauhan",
    email: "saifullahchauhan2@gmail.com",
    phone: "+92 320 0454455",
    line1: "Office #1, First Floor, Walayat Plaza",
    city: "Rawalpindi",
    state: "Punjab",
    country: "Pakistan",
    jurisdiction: "Pakistan",
    notes: "Full-service growth partnership. Agreement dated 26 Aug 2026.",
  }),
  company({
    id: "co_unlimited_insurance",
    legalName: "Unlimited Insurance",
    displayName: "Unlimited Insurance",
    companyType: "Agency",
    primaryContact: "Josh Streit",
    contactTitle: "Owner",
    email: "josh@unlimitedinsurance.test",
    city: "Miami",
    state: "FL",
    country: "United States",
    notes: "Recruitment services. Agreement dated Dec 2023.",
  }),
];

const ATTACH = "source-agreements";

function source(
  id: string,
  fileName: string,
  detectedType: string,
  companyId: string,
  uploadedAt: string,
  knowledge: {
    title: string;
    clientName: string;
    summary: string;
    monthlyFee: string;
    verticals: string[];
    recommendedTemplateId: string;
    recommendedAction: string;
    patterns: string[];
  },
): SourceDocument {
  return {
    id,
    fileName,
    contentType: "application/pdf",
    storagePath: `${ATTACH}/${fileName}`,
    uploadedAt,
    uploadedBy: actor,
    analysisStatus: "ANALYZED",
    knowledgeStatus: "approved",
    detectedType,
    analysisJson: { companyId, family: "CLIENT", ...knowledge },
    analysisConfidence: 0.94,
  };
}

const lg = {
  recommendedTemplateId: "tpl_lead_generation",
  recommendedAction: "new_lead_generation" as const,
};
const col = {
  recommendedTemplateId: "tpl_collaboration",
  recommendedAction: "new_collaboration" as const,
};
const media = {
  recommendedTemplateId: "tpl_media_buying",
  recommendedAction: "new_media_buying" as const,
};
const service = {
  recommendedTemplateId: "tpl_service_agreement",
  recommendedAction: "new_service_agreement" as const,
};

export const CLIENT_SOURCE_DOCUMENTS: SourceDocument[] = [
  source("src_prime_medical", "AMPLIFY_AND_PRIME_MEDICAL.pdf", "lead_generation_agreement", "co_prime_medical", "2025-06-20T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "Prime Medical Outlet LLC",
    summary: "Meta lead generation for Final Expense and DME, exclusive to this client, with a 14-day optimization window and advertising spend paid separately.",
    monthlyFee: "USD 1,000",
    verticals: ["Final Expense", "DME"],
    ...lg,
    patterns: ["14-day optimization", "additional verticals", "ad spend separate", "exclusive leads"],
  }),
  source("src_prime_medical_2", "LEAD_GENERATION_AGREEMENT__prime_medical_outlet.pdf", "lead_generation_agreement", "co_prime_medical", "2025-06-20T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "Prime Medical Outlet LLC",
    summary: "Duplicate of the Prime Medical lead-generation engagement dated 20 June 2025.",
    monthlyFee: "USD 1,000",
    verticals: ["Final Expense", "DME"],
    ...lg,
    patterns: ["14-day optimization", "additional verticals", "ad spend separate", "exclusive leads"],
  }),
  source("src_atleads", "ATLEADS__X_AMPLIFY.pdf", "lead_generation_agreement", "co_atleads", "2024-12-03T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "Atleads LLC",
    summary: "Affiliate-offer lead generation with a monthly retainer, 14-day optimization period, and the right to add verticals during the term.",
    monthlyFee: "USD 1,000",
    verticals: ["Affiliate offers"],
    ...lg,
    patterns: ["14-day optimization", "additional verticals", "ad spend separate", "exclusive leads"],
  }),
  source("src_atleads_2", "atleads_x_amplify.pdf", "lead_generation_agreement", "co_atleads", "2024-12-03T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "Atleads LLC",
    summary: "Duplicate of the Atleads lead-generation engagement dated 3 December 2024.",
    monthlyFee: "USD 1,000",
    verticals: ["Affiliate offers"],
    ...lg,
    patterns: ["14-day optimization", "additional verticals", "ad spend separate", "exclusive leads"],
  }),
  source("src_anchor_line", "Anchor_Line_Insurance_agreement.pdf", "collaboration_agreement", "co_anchor_line", "2026-01-11T00:00:00.000Z", {
    title: "Collaboration Agreement",
    clientName: "Anchor Line Insurance",
    summary: "Pay-per-call collaboration to deliver inbound auto-insurance calls. No outcome guarantee. Monthly service fee is USD 500.",
    monthlyFee: "USD 500",
    verticals: ["Auto insurance", "Inbound calls"],
    ...col,
    patterns: ["inbound calls", "no outcome guarantee", "pay per call"],
  }),
  source("src_rocky", "COLLABORATION_AGREEMENT.pdf", "collaboration_agreement", "co_launch_forward", "2025-03-27T00:00:00.000Z", {
    title: "Collaboration Agreement",
    clientName: "Launch Forward / Rocky Manrique",
    summary: "Pay-per-call collaboration for motor-vehicle-accident leads, including knowledge sharing on campaign method, at USD 1,000 per month.",
    monthlyFee: "USD 1,000",
    verticals: ["MVA", "Inbound calls"],
    ...col,
    patterns: ["inbound calls", "knowledge sharing", "pay per call", "no outcome guarantee"],
  }),
  source("src_rocky_2", "collaboration_agreement_with_Rocky_Manrique.pdf", "collaboration_agreement", "co_launch_forward", "2025-03-27T00:00:00.000Z", {
    title: "Collaboration Agreement",
    clientName: "Launch Forward / Rocky Manrique",
    summary: "Duplicate of the Launch Forward MVA collaboration dated 27 March 2025.",
    monthlyFee: "USD 1,000",
    verticals: ["MVA", "Inbound calls"],
    ...col,
    patterns: ["inbound calls", "knowledge sharing", "pay per call", "no outcome guarantee"],
  }),
  source("src_rocky_3", "Service_Colloboration_Agreement_with_Rocky_from_launch_forward.pdf", "collaboration_agreement", "co_launch_forward", "2025-03-27T00:00:00.000Z", {
    title: "Collaboration Agreement",
    clientName: "Launch Forward / Rocky Manrique",
    summary: "Alternate execution of the Launch Forward MVA pay-per-call collaboration.",
    monthlyFee: "USD 1,000",
    verticals: ["MVA", "Inbound calls"],
    ...col,
    patterns: ["inbound calls", "knowledge sharing", "pay per call"],
  }),
  source("src_renzo", "COLLABORATION_AGREEMENT_2.pdf", "collaboration_agreement", "co_rf_insurance", "2025-05-02T00:00:00.000Z", {
    title: "Collaboration Agreement",
    clientName: "RF Insurance Agency",
    summary: "Pay-per-call insurance collaboration with knowledge sharing and a USD 1,000 monthly fee. Performance is not guaranteed.",
    monthlyFee: "USD 1,000",
    verticals: ["Insurance", "Inbound calls"],
    ...col,
    patterns: ["inbound calls", "knowledge sharing", "pay per call", "no outcome guarantee"],
  }),
  source("src_renzo_2", "collaboration_agreement_with_Renzo.pdf", "collaboration_agreement", "co_rf_insurance", "2025-05-02T00:00:00.000Z", {
    title: "Collaboration Agreement",
    clientName: "RF Insurance Agency",
    summary: "Duplicate of the RF Insurance collaboration dated 2 May 2025.",
    monthlyFee: "USD 1,000",
    verticals: ["Insurance", "Inbound calls"],
    ...col,
    patterns: ["inbound calls", "knowledge sharing", "pay per call", "no outcome guarantee"],
  }),
  source("src_poshnee_lg", "LEAD_GENERATION_AGREEMENT.pdf", "lead_generation_agreement", "co_poshnee", "2025-06-16T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "Poshnee Tech (SMC-Private) Limited",
    summary: "Final Expense inbound-call generation on Meta, affiliate routing on a fixed rate per call, starting at USD 500 per month.",
    monthlyFee: "USD 500",
    verticals: ["Final Expense", "Inbound calls"],
    ...lg,
    patterns: ["inbound calls", "ad spend separate", "exclusive leads", "optimization"],
  }),
  source("src_poshnee_lg_2", "Lead_generation_contract_with_Anwer.pdf", "lead_generation_agreement", "co_poshnee", "2025-06-16T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "Poshnee Tech (SMC-Private) Limited",
    summary: "Duplicate of the Poshnee Tech Final Expense inbound lead-generation agreement.",
    monthlyFee: "USD 500",
    verticals: ["Final Expense", "Inbound calls"],
    ...lg,
    patterns: ["inbound calls", "ad spend separate", "exclusive leads", "optimization"],
  }),
  source("src_poshnee_media", "MEDIA_BUYING_SERVICES_AGREEMENT.pdf", "marketing_agreement", "co_poshnee", "2025-06-18T00:00:00.000Z", {
    title: "Media Buying Services Agreement",
    clientName: "Poshnee Tech (SMC-Private) Limited",
    summary: "Separate media-buying engagement: Meta campaigns, landers, pixels, pacing, and reporting. Service fee in PKR plus a minimum daily ad budget of USD 50.",
    monthlyFee: "PKR 140,000",
    verticals: ["Meta ads", "DME"],
    ...media,
    patterns: ["media buying", "daily ad budget", "ad spend separate", "optimization"],
  }),
  source("src_poshnee_media_2", "media_buying_service_agreement_with_poshnee_tech.pdf", "marketing_agreement", "co_poshnee", "2025-06-18T00:00:00.000Z", {
    title: "Media Buying Services Agreement",
    clientName: "Poshnee Tech (SMC-Private) Limited",
    summary: "Duplicate of the Poshnee Tech media-buying services agreement dated 18 June 2025.",
    monthlyFee: "PKR 140,000",
    verticals: ["Meta ads", "DME"],
    ...media,
    patterns: ["media buying", "daily ad budget", "ad spend separate", "optimization"],
  }),
  source("src_all_star", "LEAD_GENERATION_AGREEMENT_ALL_STAR__X__AMPLIFY_MEDIA__2_.pdf", "lead_generation_agreement", "co_all_star_bpo", "2025-08-14T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "All Star BPO",
    summary: "Final Expense inbound-call generation. Total monthly fee USD 2,000, with the first month split across signing and the first cycle.",
    monthlyFee: "USD 2,000",
    verticals: ["Final Expense", "Inbound calls"],
    ...lg,
    patterns: ["inbound calls", "ad spend separate", "exclusive leads", "optimization"],
  }),
  source("src_all_star_2", "LEAD_GENERATION_AGREEMENT_pbo__2_.pdf", "lead_generation_agreement", "co_all_star_bpo", "2025-08-18T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "All Star BPO",
    summary: "Follow-on All Star BPO inbound Final Expense agreement dated 18 August 2025, same commercial model.",
    monthlyFee: "USD 2,000",
    verticals: ["Final Expense", "Inbound calls"],
    ...lg,
    patterns: ["inbound calls", "ad spend separate", "exclusive leads", "optimization"],
  }),
  source("src_fpd", "LEAD_GENERATION_AGREEMENT_Amplify_Media.pdf", "lead_generation_agreement", "co_first_party_digital", "2025-05-02T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "First Party Digital",
    summary: "Workers’ compensation claim lead generation at USD 1,000 per month, due by the 5th, with a 14-day optimization period.",
    monthlyFee: "USD 1,000",
    verticals: ["Workers' compensation"],
    ...lg,
    patterns: ["14-day optimization", "additional verticals", "ad spend separate", "exclusive leads"],
  }),
  source("src_fpd_2", "LEAD_GENERATION_AGREEMENT_Date_May_2__2025.pdf", "lead_generation_agreement", "co_first_party_digital", "2025-05-02T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "First Party Digital",
    summary: "Duplicate of the First Party Digital workers’ compensation lead-generation agreement.",
    monthlyFee: "USD 1,000",
    verticals: ["Workers' compensation"],
    ...lg,
    patterns: ["14-day optimization", "additional verticals", "ad spend separate", "exclusive leads"],
  }),
  source("src_fpd_3", "LEAD_GENERATION_AGREEMENT_with___LLC_DBA.pdf", "lead_generation_agreement", "co_first_party_digital", "2025-05-02T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "Influencer Interactive, LLC DBA First Party Digital",
    summary: "Named-entity variant of the First Party Digital lead-generation agreement dated 2 May 2025.",
    monthlyFee: "USD 1,000",
    verticals: ["Workers' compensation"],
    ...lg,
    patterns: ["14-day optimization", "additional verticals", "ad spend separate", "exclusive leads"],
  }),
  source("src_exclusive", "LEAD_GENERATION_AGREEMENT_Exclusive_Media_Corporation__-_SIGNED.pdf", "lead_generation_agreement", "co_exclusive_media", "2025-11-26T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "Exclusive Media Corporation",
    summary: "Exclusive MVA lead generation. USD 1,000 retainer paid upfront, 14-day optimization, advertising spend paid separately.",
    monthlyFee: "USD 1,000",
    verticals: ["MVA"],
    ...lg,
    patterns: ["14-day optimization", "ad spend separate", "exclusive leads", "retainer"],
  }),
  source("src_exclusive_2", "LEAD_GENERATION_AGREEMENT_Exclusive_Media_Corporation__2_.pdf", "lead_generation_agreement", "co_exclusive_media", "2025-11-26T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "Exclusive Media Corporation",
    summary: "Unsigned counterpart of the Exclusive Media MVA lead-generation agreement.",
    monthlyFee: "USD 1,000",
    verticals: ["MVA"],
    ...lg,
    patterns: ["14-day optimization", "ad spend separate", "exclusive leads", "retainer"],
  }),
  source("src_capital", "LEAD_GENERATION_AGREEMENT____Date_June_17__2025.pdf", "lead_generation_agreement", "co_capital_media", "2025-06-17T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "Capital Media Agency",
    summary: "Standard Meta lead-generation retainer of USD 1,000 due by the 5th, with a 14-day optimization window and extra verticals at no setup fee.",
    monthlyFee: "USD 1,000",
    verticals: ["Lead generation"],
    ...lg,
    patterns: ["14-day optimization", "additional verticals", "ad spend separate"],
  }),
  source("src_capital_2", "lead_generation_agreement_with_Debra.pdf", "lead_generation_agreement", "co_capital_media", "2025-06-17T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "Capital Media Agency",
    summary: "Duplicate of the Capital Media Agency lead-generation agreement dated 17 June 2025.",
    monthlyFee: "USD 1,000",
    verticals: ["Lead generation"],
    ...lg,
    patterns: ["14-day optimization", "additional verticals", "ad spend separate"],
  }),
  source("src_hatim", "lead_generation_agreeement_hatim_vs_amplify.pdf", "lead_generation_agreement", "co_hatim_abbasi", "2025-09-25T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "Hatim Hameed Abbasi",
    summary: "Auto-insurance inbound-call generation. USD 1,000 billed up front each cycle, with a minimum daily ad budget of USD 50 funded by the client.",
    monthlyFee: "USD 1,000",
    verticals: ["Auto insurance", "Inbound calls"],
    ...lg,
    patterns: ["inbound calls", "daily ad budget", "ad spend separate", "exclusive leads", "optimization"],
  }),
  source("src_nettx", "nettx_market_with_amplify.pdf", "lead_generation_agreement", "co_nettx", "2025-07-16T00:00:00.000Z", {
    title: "Lead Generation Agreement",
    clientName: "Nettx Marketing",
    summary: "Affiliate and MVA lead generation at USD 2,000 per month, with a 14-day optimization period and exclusive delivery.",
    monthlyFee: "USD 2,000",
    verticals: ["Affiliate offers", "MVA"],
    ...lg,
    patterns: ["14-day optimization", "additional verticals", "ad spend separate", "exclusive leads"],
  }),
  source("src_zednex", "ZEDNEX_agreement_signed.pdf", "lead_generation_agreement", "co_zednex", "2026-07-30T00:00:00.000Z", {
    title: "Medical Billing Lead Generation Agreement",
    clientName: "ZEDNEX PRIVATE LIMITED / ZEDNEX GLOBAL LLC",
    summary: "Medical-billing lead generation. USD 1,000 monthly service fee. Outcomes are not guaranteed; advertising spend sits with the client.",
    monthlyFee: "USD 1,000",
    verticals: ["Medical billing"],
    ...lg,
    patterns: ["no outcome guarantee", "ad spend separate", "optimization"],
  }),
  source("src_baucom", "Steve_Baucom_AGREEMENT_pdf__1__copy.pdf", "collaboration_agreement", "co_lone_star", "2026-05-02T00:00:00.000Z", {
    title: "Collaboration Agreement",
    clientName: "Lone Star Financial & Senior Services LLC",
    summary: "Insurance client-acquisition collaboration for Medicare and Final Expense. USD 800 monthly fee paid upfront. No outcome guarantee.",
    monthlyFee: "USD 800",
    verticals: ["Medicare", "Final Expense"],
    ...col,
    patterns: ["no outcome guarantee", "ad spend separate", "optimization"],
  }),
  source("src_satellite", "SERVICE_AGREEMENT_Satellite_BPO_edited__1_.pdf", "service_agreement", "co_satellite_bpo", "2026-08-26T00:00:00.000Z", {
    title: "Service Agreement",
    clientName: "Satellite BPO",
    summary: "Full-service growth partnership. USD 500 monthly fee, USD 1,500 total contract value, and a minimum ad spend of USD 33 per day. No outcome guarantee.",
    monthlyFee: "USD 500",
    verticals: ["Insurance acquisition"],
    ...service,
    patterns: ["no outcome guarantee", "daily ad budget", "ad spend separate"],
  }),
  source("src_unlimited", "RECRUITMENT_SERVICE_AGREEMENT__4_.pdf", "service_agreement", "co_unlimited_insurance", "2023-12-01T00:00:00.000Z", {
    title: "Recruitment Service Agreement",
    clientName: "Unlimited Insurance",
    summary: "Recruitment services for Unlimited Insurance in Miami. Placement fees between USD 200 and USD 300 per hire. Distinct from lead-generation retainers.",
    monthlyFee: "USD 200–300 per hire",
    verticals: ["Recruitment"],
    ...service,
    patterns: ["recruitment"],
  }),
];

export const CLIENT_KNOWLEDGE_FINDINGS: KnowledgeFinding[] = [
  {
    id: "kf_optimization_period",
    title: "14-day campaign optimization period",
    category: "Client · Term",
    occurrenceCount: 16,
    sampleText: "Lead-generation agreements grant a diagnostic window to test creatives, targeting, and strategy before performance is judged.",
    suggestedClauseId: "cl_optimization_period",
    sourceDocumentIds: ["src_prime_medical", "src_atleads", "src_fpd", "src_exclusive", "src_capital", "src_nettx"],
    decision: "approve_standard",
    status: "resolved",
    createdAt,
  },
  {
    id: "kf_extra_verticals",
    title: "Additional campaign verticals without setup fees",
    category: "Client · Scope",
    occurrenceCount: 12,
    sampleText: "Clients may add niches or verticals during the term without extra setup charges. Media spend remains payable by the client.",
    suggestedClauseId: "cl_additional_verticals",
    sourceDocumentIds: ["src_prime_medical", "src_atleads", "src_fpd", "src_capital", "src_nettx"],
    decision: "approve_standard",
    status: "resolved",
    createdAt,
  },
  {
    id: "kf_no_guarantee",
    title: "No guarantee of leads, sales, or ROI",
    category: "Client · Commercial",
    occurrenceCount: 14,
    sampleText: "Fees are for services rendered. Platform, market, and client-side conversion factors sit outside Amplify's control.",
    suggestedClauseId: "cl_no_guarantee",
    sourceDocumentIds: ["src_anchor_line", "src_rocky", "src_renzo", "src_zednex", "src_baucom", "src_satellite"],
    decision: "approve_standard",
    status: "resolved",
    createdAt,
  },
  {
    id: "kf_inbound_calls",
    title: "Inbound call generation and live routing",
    category: "Client · Services",
    occurrenceCount: 10,
    sampleText: "Collaborations and several lead-gen retainers require live inbound calls (auto, Final Expense, MVA) routed to the client's closers.",
    suggestedClauseId: "cl_inbound_calls",
    sourceDocumentIds: ["src_anchor_line", "src_rocky", "src_renzo", "src_poshnee_lg", "src_all_star", "src_hatim"],
    decision: "approve_optional",
    status: "resolved",
    createdAt,
  },
  {
    id: "kf_ad_spend",
    title: "Advertising spend paid separately",
    category: "Client · Commercial",
    occurrenceCount: 20,
    sampleText: "Media budget is the client's cost, often with a minimum daily spend, and is not included in Amplify's retainer.",
    suggestedClauseId: "cl_ad_spend",
    sourceDocumentIds: ["src_prime_medical", "src_hatim", "src_poshnee_media", "src_satellite", "src_zednex"],
    decision: "approve_standard",
    status: "resolved",
    createdAt,
  },
  {
    id: "kf_media_buying",
    title: "Media buying as a distinct engagement",
    category: "Client · Services",
    occurrenceCount: 2,
    sampleText: "Poshnee Tech used a media-buying agreement covering Meta campaigns, landers, pixels, pacing, and reporting — separate from its lead-gen retainer.",
    suggestedClauseId: "cl_media_buying_scope",
    sourceDocumentIds: ["src_poshnee_media", "src_poshnee_media_2"],
    decision: "approve_standard",
    status: "resolved",
    createdAt,
  },
  {
    id: "kf_collaboration",
    title: "Pay-per-call collaboration model",
    category: "Client · Commercial",
    occurrenceCount: 7,
    sampleText: "Agency and affiliate collaborations cover inbound calls or leads plus a monthly fee, often with knowledge sharing on campaign method.",
    suggestedClauseId: "cl_collaboration_scope",
    sourceDocumentIds: ["src_anchor_line", "src_rocky", "src_renzo", "src_baucom"],
    decision: "approve_standard",
    status: "resolved",
    createdAt,
  },
];
