import type { KnowledgeFinding, Person, SourceDocument } from "@/lib/types";

const createdAt = "2026-01-15T09:00:00.000Z";
const actor = "user_super_admin";

function addr(line1: string, city: string, province: string, country = "Pakistan") {
  return { line1, line2: "", city, state: province, postalCode: "", country };
}

function person(input: {
  id: string;
  firstName: string;
  lastName: string;
  fullLegalName?: string;
  fatherName?: string;
  identityNumber?: string;
  dateOfBirth?: string;
  email: string;
  phone?: string;
  line1?: string;
  city?: string;
  province?: string;
  employeeId: string;
  type?: Person["type"];
  currentJobTitle: string;
  department: string;
  employmentStatus?: Person["employmentStatus"];
  employmentStartDate?: string;
  currentSalary: number;
  salaryCurrency?: string;
  notes: string;
}): Person {
  const city = input.city ?? "Rawalpindi";
  const province = input.province ?? "Punjab";
  const address = addr(input.line1 ?? "", city, province);
  return {
    id: input.id,
    firstName: input.firstName,
    middleName: "",
    lastName: input.lastName,
    fullLegalName: input.fullLegalName ?? `${input.firstName} ${input.lastName}`,
    fatherName: input.fatherName ?? "",
    identityNumber: input.identityNumber ?? "",
    dateOfBirth: input.dateOfBirth ?? "",
    email: input.email,
    phone: input.phone ?? "",
    residentialAddress: address,
    permanentAddress: address,
    city,
    province,
    country: "Pakistan",
    employeeId: input.employeeId,
    type: input.type ?? "employee",
    currentJobTitle: input.currentJobTitle,
    department: input.department,
    reportingManager: "Basit Gilani",
    employmentStatus: input.employmentStatus ?? "active",
    employmentStartDate: input.employmentStartDate ?? "",
    currentSalary: input.currentSalary,
    salaryCurrency: input.salaryCurrency ?? "PKR",
    salaryFrequency: "monthly",
    notes: input.notes,
    createdAt,
    updatedAt: createdAt,
    createdBy: actor,
  };
}

export const EMPLOYMENT_PEOPLE: Person[] = [
  person({
    id: "p_zunaira_yaqoob",
    firstName: "Zunaira",
    lastName: "Yaqoob",
    fatherName: "Yaqoob Masih",
    identityNumber: "71501-1675637-2",
    dateOfBirth: "2007-08-25",
    email: "zunaira.yaqoob@amplify.test",
    line1: "Mohallah Pakistan Colony, Jutial",
    city: "Gilgit",
    province: "Gilgit-Baltistan",
    employeeId: "AMP-EMP-1101",
    currentJobTitle: "Appointment Setter",
    department: "Sales",
    employmentStartDate: "2026-08-18",
    currentSalary: 100000,
    notes: "On-site appointment setter. Night shift 17:00–03:00. 10-day paid probation.",
  }),
  person({
    id: "p_maria_ali",
    firstName: "Maria",
    lastName: "Ali",
    identityNumber: "37405-6801169-8",
    email: "Mariah.ManagingDirector@gmail.com",
    line1: "Apartment 123B, Floor S-8, QJ Heights, Bahria Town",
    city: "Islamabad",
    province: "Islamabad Capital Territory",
    employeeId: "AMP-EMP-1102",
    currentJobTitle: "Appointment Setter",
    department: "Sales",
    employmentStartDate: "2026-06-25",
    currentSalary: 500,
    salaryCurrency: "USD",
    notes: "Agency appointment setter assigned across client and internal campaigns. Commission on internal campaigns.",
  }),
  person({
    id: "p_adeel_asghar",
    firstName: "Adeel",
    lastName: "Asghar",
    fatherName: "Ali Asghar",
    identityNumber: "35101-7811441-9",
    email: "real.adeelasghar@gmail.com",
    phone: "03005012320",
    line1: "Mohalla Muhajir Wara No. 2, Dak Khana Allahabad",
    city: "Kasur",
    employeeId: "AMP-EMP-1103",
    currentJobTitle: "Media Buyer",
    department: "Media",
    employmentStartDate: "2025-08-12",
    currentSalary: 100000,
    notes: "Media buyer. Salary payable within first 10 days of each month.",
  }),
  person({
    id: "p_nida_ajaz",
    firstName: "Nida",
    lastName: "Ajaz",
    fatherName: "Malik Ajaz Ahmed",
    identityNumber: "13101-4011519-4",
    dateOfBirth: "1997-12-02",
    email: "mbaawais456@gmail.com",
    phone: "03105888399",
    line1: "Riffat Shaheen Road, Street 2, Opposite Madina Car Parking, KRL Road",
    employeeId: "AMP-EMP-1104",
    currentJobTitle: "GHL Executive",
    department: "Operations",
    employmentStartDate: "2026-06-16",
    currentSalary: 25000,
    notes: "Converted from GHL intern (PKR 10,000 stipend) to full-time GHL Executive.",
  }),
  person({
    id: "p_arham_awan",
    firstName: "Arham",
    lastName: "Awan",
    fullLegalName: "Arham Tahir Awan",
    identityNumber: "42301-3774046-9",
    email: "arhamtawan@gmail.com",
    phone: "+923473179123",
    line1: "House 191, Street 98, I-8/4",
    city: "Islamabad",
    province: "Islamabad Capital Territory",
    employeeId: "AMP-EMP-1105",
    currentJobTitle: "Outsourced Application Support Engineer",
    department: "Engineering",
    employmentStartDate: "2026-06-11",
    currentSalary: 100,
    salaryCurrency: "USD",
    notes: "Supports operational and maintenance work with the development team.",
  }),
  person({
    id: "p_anam_harmain",
    firstName: "Anam",
    lastName: "Harmain",
    fatherName: "Muhammad Harmain",
    identityNumber: "34402-2323700-8",
    email: "mrsharmain12@gmail.com",
    phone: "03315220122",
    line1: "House #88, Street #4, Block B, Rawal Enclave, near Kuri Sheher",
    city: "Islamabad",
    province: "Islamabad Capital Territory",
    employeeId: "AMP-EMP-1106",
    currentJobTitle: "Creative Manager & Graphic Designer",
    department: "Creative",
    employmentStartDate: "2025-05-17",
    currentSalary: 30000,
    notes: "Part-time creative lead. No fixed hours.",
  }),
  person({
    id: "p_asif_masih",
    firstName: "Asif",
    lastName: "Masih",
    fatherName: "Gulzar Masih",
    identityNumber: "37405-0595835-5",
    email: "asif.masih@amplify.test",
    phone: "03495728072",
    employeeId: "AMP-EMP-1107",
    currentJobTitle: "Office Boy & Security Guard",
    department: "Operations",
    employmentStartDate: "2026-04-18",
    currentSalary: 37000,
    notes: "Office support and security. Agreement dated 15 June 2026.",
  }),
  person({
    id: "p_dure_shawar",
    firstName: "Dur-e-Shawar",
    lastName: "Nasir",
    fatherName: "Nasir Ahmed",
    identityNumber: "35202-2560524-4",
    email: "diya02618@gmail.com",
    phone: "03218583029",
    line1: "House #695, Block D, Sher Shah Colony, Raiwind Road",
    city: "Lahore",
    employeeId: "AMP-EMP-1108",
    currentJobTitle: "Creative Manager & Graphic Designer",
    department: "Creative",
    employmentStartDate: "2026-01-01",
    currentSalary: 50000,
    notes: "Night-shift creative manager. Original salary PKR 35,000; incremented to PKR 50,000 from 1 Aug 2026.",
  }),
  person({
    id: "p_ijaz_ansari",
    firstName: "Hafiz",
    lastName: "Ijaz",
    fullLegalName: "Hafiz Muhammad Ijaz",
    fatherName: "Muhammad Anwar",
    identityNumber: "33100-9838550-9",
    email: "ijazansari781@gmail.com",
    phone: "03034545439",
    line1: "House #195, E-Block, FED",
    employeeId: "AMP-EMP-1109",
    currentJobTitle: "Website Designer",
    department: "Creative",
    employmentStartDate: "2024-12-01",
    currentSalary: 50000,
    notes: "Part-time website designer.",
  }),
  person({
    id: "p_hassan_zubair",
    firstName: "Hassan",
    lastName: "Zubair",
    fullLegalName: "Malik Hassan Zubair",
    fatherName: "Malik Zubair Ahmad",
    identityNumber: "31302-9988596-3",
    email: "hassanmalik99885@gmail.com",
    phone: "03442440427",
    line1: "Plot # 258/B, SH-I, Sector 11-1/2, Muhammad Mustafa Colony, Orangi Town",
    city: "Karachi",
    province: "Sindh",
    employeeId: "AMP-EMP-1110",
    currentJobTitle: "Video Editor",
    department: "Creative",
    employmentStartDate: "2025-01-01",
    currentSalary: 50000,
    notes: "Full-time video editor. 10-hour shifts coordinated to project needs.",
  }),
  person({
    id: "p_kanwal_shehzadi",
    firstName: "Kanwal",
    lastName: "Shehzadi",
    fatherName: "Pervez Akhtar",
    identityNumber: "82101-6613615-4",
    email: "kanwalshehzadi663@gmail.com",
    phone: "03100000292",
    line1: "Bagh Azad Kashmir, Dhand Gulistan, Chatir Number 1",
    city: "Bagh",
    province: "Azad Kashmir",
    employeeId: "AMP-EMP-1111",
    currentJobTitle: "Junior Graphic Designer",
    department: "Creative",
    employmentStartDate: "2025-05-16",
    currentSalary: 30000,
    notes: "Full-time junior designer supporting the creative manager.",
  }),
  person({
    id: "p_sikandar_naqvi",
    firstName: "Syed",
    lastName: "Naqvi",
    fullLegalName: "Syed Sikandar Ali Naqvi",
    fatherName: "Syed Zulfiqar Ali",
    identityNumber: "61101-9715456-3",
    email: "sikku.a12@gmail.com",
    phone: "03369415505",
    line1: "House no 26B, Sector 4A, Khayaban e Sirsyed",
    employeeId: "AMP-EMP-1112",
    currentJobTitle: "AI Video Editor & Content Creator",
    department: "Creative",
    employmentStartDate: "2026-01-01",
    currentSalary: 50000,
    notes: "Joined as AI video intern (PKR 10,000) on 1 Jan 2026; full-time AI video editor from 15 Jun 2026 at PKR 50,000.",
  }),
  person({
    id: "p_raheel_mehmood",
    firstName: "Raheel",
    lastName: "Mehmood",
    fullLegalName: "Hafiz Muhammad Raheel",
    fatherName: "Tariq Mehmood",
    identityNumber: "37201-5418873-5",
    email: "raheelmuhammad300@gmail.com",
    phone: "03350783246",
    line1: "Allama Iqbal Colony C-8, Sumbalgah, Kahuta",
    employeeId: "AMP-EMP-1113",
    currentJobTitle: "Media Buyer",
    department: "Media",
    employmentStartDate: "2025-05-08",
    currentSalary: 100000,
    notes: "Media buyer. 30-day notice.",
  }),
  person({
    id: "p_ali_subhan",
    firstName: "Ali",
    lastName: "Subhan",
    identityNumber: "36302-8599132-3",
    email: "alisubhanbaloch99@gmail.com",
    phone: "+923021771900",
    line1: "House No. 412, Gulshan-e-Wahid Colony, near Wapda Town Phase 1",
    city: "Multan",
    employeeId: "AMP-EMP-1114",
    currentJobTitle: "Business Development Manager",
    department: "Sales",
    employmentStatus: "probation",
    employmentStartDate: "2026-08-07",
    currentSalary: 50000,
    notes: "90-day trial as BDM/BDR. Permanent offer after successful trial.",
  }),
  person({
    id: "p_abeera_shaheen",
    firstName: "Abeera",
    lastName: "Shaheen",
    identityNumber: "37402-8131603-2",
    email: "abeera67781@gmail.com",
    phone: "03441803916",
    line1: "House No# 89, Street# 15-C, Babar Colony, Shaheed Chowk",
    employeeId: "AMP-INT-1115",
    type: "intern",
    currentJobTitle: "Facebook Ads Intern",
    department: "Media",
    employmentStartDate: "2026-07-01",
    currentSalary: 10000,
    notes: "Internship stipend PKR 10,000. Hours set by the company.",
  }),
  person({
    id: "p_suleyman_raja",
    firstName: "Suleyman",
    lastName: "Raja",
    fullLegalName: "M Suleyman Saleem Raja",
    identityNumber: "34101-3423068-9",
    email: "suleymanraja8@gmail.com",
    phone: "03055673835",
    line1: "House 301, Street 4, Sector C, Askari 10",
    employeeId: "AMP-EMP-1116",
    currentJobTitle: "Business Development Representative",
    department: "Sales",
    employmentStatus: "probation",
    employmentStartDate: "2026-08-31",
    currentSalary: 100000,
    notes: "BDR with variable close commission. Two-month probation.",
  }),
  person({
    id: "p_musab_aslam",
    firstName: "Musab",
    lastName: "Aslam",
    fullLegalName: "Musab Bin Aslam",
    fatherName: "Muhammad Aslam",
    email: "musab@amplifymediatechnologies.com",
    line1: "House #948, KRL Road, Babar Colony, Near Rajgan Haveli, Dhoke Gangal",
    employeeId: "AMP-EMP-1117",
    currentJobTitle: "Chief Technical Officer",
    department: "Engineering",
    employmentStartDate: "2026-08-01",
    currentSalary: 115000,
    notes: "Executive CTO. GHL is excluded from scope. Project-based development commission in addition to salary.",
  }),
  person({
    id: "p_waseem_abbas",
    firstName: "Muhammad",
    lastName: "Abbas",
    fullLegalName: "Muhammad Waseem Abbas",
    email: "waseem@amplifymediatechnologies.com",
    line1: "Hassu Balail, Tehsil Ahmad Pur Sial",
    city: "Jhang",
    employeeId: "AMP-EMP-1118",
    currentJobTitle: "Chief Operating Officer",
    department: "Operations",
    employmentStartDate: "2025-10-13",
    currentSalary: 100000,
    notes: "Hired as Media Buyer on 13 Oct 2025. Promoted to COO effective 1 Aug 2026.",
  }),
];

function source(
  id: string,
  fileName: string,
  detectedType: string,
  personId: string,
  uploadedAt: string,
  knowledge: {
    title: string;
    partyName: string;
    summary: string;
    compensation: string;
    role: string;
    recommendedTemplateId: string;
    recommendedAction: string;
    patterns: string[];
  },
): SourceDocument {
  return {
    id,
    fileName,
    contentType: "application/pdf",
    storagePath: `source-agreements/${fileName}`,
    uploadedAt,
    uploadedBy: actor,
    analysisStatus: "ANALYZED",
    knowledgeStatus: "approved",
    detectedType,
    analysisJson: { family: "EMPLOYMENT", personId, ...knowledge },
    analysisConfidence: 0.93,
  };
}

const ea = { recommendedTemplateId: "tpl_employment_standard", recommendedAction: "hire" };
const setter = { recommendedTemplateId: "tpl_employment_appointment_setter", recommendedAction: "hire" };
const promo = { recommendedTemplateId: "tpl_promotion_amended", recommendedAction: "promote" };
const salary = { recommendedTemplateId: "tpl_promotion_amended", recommendedAction: "change_salary" };

export const EMPLOYMENT_SOURCE_DOCUMENTS: SourceDocument[] = [
  source("src_zunaira", "Agreement__APPOINTMENT_SETTER_Zunaira_Yaqoob__1_.pdf__1_.pdf", "employment_appointment_setter", "p_zunaira_yaqoob", "2026-08-18T00:00:00.000Z", {
    title: "Appointment Setter Employment Agreement",
    partyName: "Zunaira Yaqoob",
    summary: "On-site appointment setter on a night shift (17:00–03:00) at PKR 100,000 per month, with a 10-day paid probation.",
    compensation: "PKR 100,000 / month",
    role: "Appointment Setter",
    ...setter,
    patterns: ["appointment setter", "paid probation", "night shift", "client data"],
  }),
  source("src_maria", "AGREEMENT__Maria_Ali__1_.pdf", "employment_appointment_setter", "p_maria_ali", "2026-06-25T00:00:00.000Z", {
    title: "Employment Agreement (Agency Role)",
    partyName: "Maria Ali",
    summary: "Appointment setter assigned across external clients and internal campaigns. USD 500 monthly (or PKR equivalent) plus internal-campaign commission.",
    compensation: "USD 500 / month",
    role: "Appointment Setter",
    ...setter,
    patterns: ["appointment setter", "commission", "multi-client assignment", "client data"],
  }),
  source("src_adeel", "emploement_agreement_with_Adeel.pdf", "employment_standard", "p_adeel_asghar", "2025-08-12T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Adeel Asghar",
    summary: "Media buyer at PKR 100,000 per month, payable within the first 10 days. 30-day notice. IP and confidentiality covered.",
    compensation: "PKR 100,000 / month",
    role: "Media Buyer",
    ...ea,
    patterns: ["media buyer", "10-day payroll", "30-day notice", "IP ownership"],
  }),
  source("src_adeel_2", "emploement_agreement_with_Adeel_1_.pdf", "employment_standard", "p_adeel_asghar", "2025-08-12T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Adeel Asghar",
    summary: "Duplicate of Adeel Asghar’s media-buyer employment agreement dated 12 August 2025.",
    compensation: "PKR 100,000 / month",
    role: "Media Buyer",
    ...ea,
    patterns: ["media buyer", "10-day payroll", "30-day notice", "IP ownership"],
  }),
  source("src_nida", "_employement_agreement_Nida_Ajaz___.pdf__1_.pdf", "employment_standard", "p_nida_ajaz", "2026-06-16T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Nida Ajaz",
    summary: "Converts a GHL internship (PKR 10,000 stipend) into a full-time GHL Executive role at PKR 25,000 from 16 June 2026.",
    compensation: "PKR 25,000 / month",
    role: "GHL Executive",
    ...ea,
    patterns: ["intern conversion", "GHL", "10-day payroll"],
  }),
  source("src_arham", "employement_agreement_Arham_Tahir_Awan.pdf", "employment_standard", "p_arham_awan", "2026-06-11T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Arham Tahir Awan",
    summary: "Outsourced application support engineer working with the development team. USD 100 per month.",
    compensation: "USD 100 / month",
    role: "Outsourced Application Support Engineer",
    ...ea,
    patterns: ["engineering", "30-day notice", "IP ownership"],
  }),
  source("src_anam", "employement_agreement_anam_harmain_1.pdf", "employment_standard", "p_anam_harmain", "2025-05-17T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Anam Harmain",
    summary: "Part-time Creative Manager & Graphic Designer at PKR 30,000, with no fixed hours and 30-day notice.",
    compensation: "PKR 30,000 / month",
    role: "Creative Manager & Graphic Designer",
    ...ea,
    patterns: ["part-time", "creative", "salary deductions", "30-day notice", "IP ownership"],
  }),
  source("src_anam_2", "employement_agreement_anam_harmain_1_1_.pdf", "employment_standard", "p_anam_harmain", "2025-05-17T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Anam Harmain",
    summary: "Duplicate of Anam Harmain’s part-time creative manager agreement dated 17 May 2025.",
    compensation: "PKR 30,000 / month",
    role: "Creative Manager & Graphic Designer",
    ...ea,
    patterns: ["part-time", "creative", "salary deductions", "30-day notice"],
  }),
  source("src_asif", "employement_agreement_Asif_Masih__.pdf.pdf", "employment_standard", "p_asif_masih", "2026-06-15T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Asif Masih",
    summary: "Office boy and security guard. Employment commenced 18 April 2026. Monthly salary PKR 37,000.",
    compensation: "PKR 37,000 / month",
    role: "Office Boy & Security Guard",
    ...ea,
    patterns: ["operations"],
  }),
  source("src_dure", "employement_agreement_Dur-e-Shawar_nasir.pdf.pdf", "employment_standard", "p_dure_shawar", "2026-01-01T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Dur-e-Shawar Nasir",
    summary: "Creative Manager & Graphic Designer on a night shift at PKR 35,000, with salary-deduction and 30-day notice terms.",
    compensation: "PKR 35,000 / month",
    role: "Creative Manager & Graphic Designer",
    ...ea,
    patterns: ["night shift", "salary deductions", "30-day notice", "IP ownership"],
  }),
  source("src_dure_increment", "EMPLOYMENT_CONTRACT_EXTENSION___SALARY_INCREMENT_AGREEMENT_DUR-E-SHAWAR__1_.pdf", "salary_amendment", "p_dure_shawar", "2026-08-01T00:00:00.000Z", {
    title: "Employment Contract Extension & Salary Increment",
    partyName: "Dur-e-Shawar Nasir",
    summary: "Amends the 1 Jan 2026 employment agreement. Basic salary rises from PKR 35,000 to PKR 50,000 from 1 Aug 2026. Other terms continue.",
    compensation: "PKR 50,000 / month",
    role: "Creative Manager & Graphic Designer",
    ...salary,
    patterns: ["salary increment", "amends original", "30-day notice"],
  }),
  source("src_ijaz", "EMPLOYEMENT_AGREEMENT_IJAZ.pdf", "employment_standard", "p_ijaz_ansari", "2024-12-01T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Hafiz Muhammad Ijaz",
    summary: "Part-time website designer at PKR 50,000, payable within 10 days, with salary-deduction and 30-day notice clauses.",
    compensation: "PKR 50,000 / month",
    role: "Website Designer",
    ...ea,
    patterns: ["part-time", "salary deductions", "30-day notice", "IP ownership"],
  }),
  source("src_ijaz_2", "EMPLOYEMENT_AGREEMENT_IJAZ_1_.pdf", "employment_standard", "p_ijaz_ansari", "2024-12-01T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Hafiz Muhammad Ijaz",
    summary: "Duplicate of Hafiz Muhammad Ijaz’s website-designer agreement dated 1 December 2024.",
    compensation: "PKR 50,000 / month",
    role: "Website Designer",
    ...ea,
    patterns: ["part-time", "salary deductions", "30-day notice"],
  }),
  source("src_hassan", "employement_agreement_hassan.pdf", "employment_standard", "p_hassan_zubair", "2025-01-01T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Malik Hassan Zubair",
    summary: "Full-time video editor at PKR 50,000. Ten-hour days. Work product is Company IP. 30-day notice.",
    compensation: "PKR 50,000 / month",
    role: "Video Editor",
    ...ea,
    patterns: ["video editor", "salary deductions", "30-day notice", "IP ownership"],
  }),
  source("src_hassan_2", "employement_agreement_hassan_1_.pdf", "employment_standard", "p_hassan_zubair", "2025-01-01T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Malik Hassan Zubair",
    summary: "Duplicate of Malik Hassan Zubair’s video-editor employment agreement.",
    compensation: "PKR 50,000 / month",
    role: "Video Editor",
    ...ea,
    patterns: ["video editor", "salary deductions", "30-day notice", "IP ownership"],
  }),
  source("src_kanwal", "employement_agreement_kanwal.pdf", "employment_standard", "p_kanwal_shehzadi", "2025-05-16T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Kanwal Shehzadi",
    summary: "Full-time junior graphic designer at PKR 30,000. 12-month client-protection language and 30-day notice.",
    compensation: "PKR 30,000 / month",
    role: "Junior Graphic Designer",
    ...ea,
    patterns: ["graphic designer", "client protection", "salary deductions", "30-day notice", "IP ownership"],
  }),
  source("src_kanwal_2", "employement_agreement_kanwal_1_.pdf", "employment_standard", "p_kanwal_shehzadi", "2025-05-16T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Kanwal Shehzadi",
    summary: "Duplicate of Kanwal Shehzadi’s junior graphic designer agreement dated 16 May 2025.",
    compensation: "PKR 30,000 / month",
    role: "Junior Graphic Designer",
    ...ea,
    patterns: ["graphic designer", "client protection", "30-day notice"],
  }),
  source("src_sikandar_intern", "employement_agreement_Syed_Sikandar_Ali_Naqvi.pdf__2_.pdf", "internship_agreement", "p_sikandar_naqvi", "2026-01-01T00:00:00.000Z", {
    title: "Internship / Employment Agreement",
    partyName: "Syed Sikandar Ali Naqvi",
    summary: "Joined 1 Jan 2026 as an intern for AI video generation and content at PKR 10,000 per month.",
    compensation: "PKR 10,000 / month",
    role: "AI Video Intern",
    ...ea,
    patterns: ["internship", "AI video", "10-day payroll"],
  }),
  source("src_sikandar", "employement_agreement_Syed_Sikandar_Ali_Naqvi.pdf__3_.pdf", "employment_standard", "p_sikandar_naqvi", "2026-06-15T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Syed Sikandar Ali Naqvi",
    summary: "Full-time AI video editor and content creator from 15 June 2026 at PKR 50,000, nine hours per day.",
    compensation: "PKR 50,000 / month",
    role: "AI Video Editor & Content Creator",
    ...ea,
    patterns: ["video editor", "intern conversion", "30-day notice", "IP ownership"],
  }),
  source("src_raheel", "employement_agreement_with_Raheel.pdf", "employment_standard", "p_raheel_mehmood", "2025-05-08T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Hafiz Muhammad Raheel",
    summary: "Media buyer at PKR 100,000 per month with 30-day notice and salary-deduction language.",
    compensation: "PKR 100,000 / month",
    role: "Media Buyer",
    ...ea,
    patterns: ["media buyer", "10-day payroll", "30-day notice", "salary deductions"],
  }),
  source("src_raheel_2", "employement_agreement_with_Raheel_1_.pdf", "employment_standard", "p_raheel_mehmood", "2025-05-08T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Hafiz Muhammad Raheel",
    summary: "Duplicate of Hafiz Muhammad Raheel’s media-buyer agreement dated 8 May 2025.",
    compensation: "PKR 100,000 / month",
    role: "Media Buyer",
    ...ea,
    patterns: ["media buyer", "30-day notice"],
  }),
  source("src_ali_trial", "EMPLOYMENT_AGREEMENT__TRIAL_PERIOD__Ali__1_.pdf", "employment_standard", "p_ali_subhan", "2026-08-07T00:00:00.000Z", {
    title: "Employment Agreement (Trial Period)",
    partyName: "Ali Subhan",
    summary: "BDM/BDR on a 90-day trial at PKR 50,000. Permanent offer is contingent on completing the trial.",
    compensation: "PKR 50,000 / month",
    role: "Business Development Manager",
    ...ea,
    patterns: ["trial period", "probation", "BDR"],
  }),
  source("src_abeera", "INTERNSHIP_AGREEMENT__Abeera_shaheen_copy.pdf", "internship_agreement", "p_abeera_shaheen", "2026-07-01T00:00:00.000Z", {
    title: "Internship Agreement",
    partyName: "Abeera Shaheen",
    summary: "Facebook Ads intern from 1 July 2026. Monthly stipend PKR 10,000. Hours set by the company.",
    compensation: "PKR 10,000 / month",
    role: "Facebook Ads Intern",
    ...ea,
    patterns: ["internship", "stipend", "media"],
  }),
  source("src_suleyman", "EMPLOYMENT_AGREEMENT_M_Suleyman_Saleem_Raja__1___1_.pdf", "employment_standard", "p_suleyman_raja", "2026-08-31T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "M Suleyman Saleem Raja",
    summary: "Business development representative at PKR 100,000 plus variable close commission. Two-month probation.",
    compensation: "PKR 100,000 / month + commission",
    role: "Business Development Representative",
    ...ea,
    patterns: ["BDR", "commission", "probation", "client protection"],
  }),
  source("src_musab", "EMPLOYMENT_AGREEMENT_CHIEF_TECHNICAL_OFFICER__CTO_Musab_Bin_Aslam.pdf__1__copy_2.pdf", "employment_executive", "p_musab_aslam", "2026-08-01T00:00:00.000Z", {
    title: "CTO Employment Agreement",
    partyName: "Musab Bin Aslam",
    summary: "Chief Technical Officer from 1 August 2026 at PKR 115,000 plus project-based development commission. GHL work is expressly excluded.",
    compensation: "PKR 115,000 / month + project commission",
    role: "Chief Technical Officer",
    ...ea,
    patterns: ["executive", "CTO", "commission", "GHL exclusion"],
  }),
  source("src_waseem", "employement_agreemnet_waseem.pdf", "employment_standard", "p_waseem_abbas", "2025-10-13T00:00:00.000Z", {
    title: "Employment Agreement",
    partyName: "Muhammad Waseem Abbas",
    summary: "Original media-buyer employment from 13 October 2025 at PKR 100,000 per month.",
    compensation: "PKR 100,000 / month",
    role: "Media Buyer",
    ...ea,
    patterns: ["media buyer", "10-day payroll", "30-day notice"],
  }),
  source("src_waseem_promo", "Signed_PROMOTION___AMENDED_EMPLOYMENT_AGREEMENT_Muhammad_Waseem_Abbas.pdf", "promotion_amended_employment", "p_waseem_abbas", "2026-08-01T00:00:00.000Z", {
    title: "Promotion & Amended Employment Agreement",
    partyName: "Muhammad Waseem Abbas",
    summary: "Promotes the 13 Oct 2025 media-buyer agreement to Chief Operating Officer effective 1 August 2026. Amends rather than replaces the original.",
    compensation: "PKR 100,000 / month",
    role: "Chief Operating Officer",
    ...promo,
    patterns: ["promotion", "amends original", "executive", "COO"],
  }),
];

export const EMPLOYMENT_KNOWLEDGE_FINDINGS: KnowledgeFinding[] = [
  {
    id: "kf_notice_30",
    title: "Thirty-day written notice",
    category: "Employment · Termination",
    occurrenceCount: 16,
    sampleText: "Most staff agreements terminate on 30 days’ written notice, with immediate termination reserved for misconduct or material breach.",
    suggestedClauseId: "cl_termination_notice",
    sourceDocumentIds: ["src_adeel", "src_anam", "src_dure", "src_ijaz", "src_hassan", "src_kanwal", "src_raheel"],
    decision: "approve_standard",
    status: "resolved",
    createdAt,
  },
  {
    id: "kf_salary_deductions",
    title: "Salary deductions for non-performance",
    category: "Employment · Compensation",
    occurrenceCount: 10,
    sampleText: "Creative and media agreements allow deductions where the employee is unresponsive in working hours, misses deadlines, or fails delivery standards.",
    suggestedClauseId: "cl_compensation_monthly",
    sourceDocumentIds: ["src_anam", "src_dure", "src_ijaz", "src_hassan", "src_kanwal", "src_raheel"],
    decision: "approve_standard",
    status: "resolved",
    createdAt,
  },
  {
    id: "kf_ip_work_product",
    title: "Company owns work product",
    category: "Employment · IP",
    occurrenceCount: 14,
    sampleText: "Videos, designs, ads, and other work created during employment are Company intellectual property.",
    suggestedClauseId: "cl_ip_ownership",
    sourceDocumentIds: ["src_adeel", "src_anam", "src_hassan", "src_kanwal", "src_sikandar"],
    decision: "approve_standard",
    status: "resolved",
    createdAt,
  },
  {
    id: "kf_payroll_10_days",
    title: "Salary paid within ten days",
    category: "Employment · Compensation",
    occurrenceCount: 12,
    sampleText: "Monthly salary is typically due within the first ten days of the following month.",
    suggestedClauseId: "cl_compensation_monthly",
    sourceDocumentIds: ["src_adeel", "src_zunaira", "src_anam", "src_sikandar"],
    decision: "approve_standard",
    status: "resolved",
    createdAt,
  },
  {
    id: "kf_paid_probation",
    title: "Paid probation or trial period",
    category: "Employment · Probation",
    occurrenceCount: 3,
    sampleText: "New hires use a paid probation or trial: 10 days (appointment setter), 2 months (BDR), or 90 days (BDM trial).",
    suggestedClauseId: "cl_probation_paid",
    sourceDocumentIds: ["src_zunaira", "src_suleyman", "src_ali_trial"],
    decision: "approve_standard",
    status: "resolved",
    createdAt,
  },
  {
    id: "kf_intern_stipend",
    title: "Internship stipend then conversion",
    category: "Employment · Internship",
    occurrenceCount: 3,
    sampleText: "Internships start at about PKR 10,000. Nida converted to GHL Executive; Sikandar converted to full-time AI video editor.",
    suggestedClauseId: "cl_compensation_monthly",
    sourceDocumentIds: ["src_abeera", "src_nida", "src_sikandar_intern"],
    decision: "approve_optional",
    status: "resolved",
    createdAt,
  },
  {
    id: "kf_promotion_amends",
    title: "Promotion and salary changes amend the original",
    category: "Employment · Amendment",
    occurrenceCount: 2,
    sampleText: "Waseem’s COO promotion and Dur-e-Shawar’s increment amend the existing employment agreement instead of replacing it.",
    suggestedClauseId: "cl_amendment_recitals",
    sourceDocumentIds: ["src_waseem_promo", "src_dure_increment"],
    decision: "approve_standard",
    status: "resolved",
    createdAt,
  },
  {
    id: "kf_setter_client_data",
    title: "Appointment setters handle client personal data",
    category: "Employment · Role",
    occurrenceCount: 2,
    sampleText: "Appointment-setter agreements cover multi-client campaigns and require protection of lead and client contact data.",
    suggestedClauseId: "cl_data_protection",
    sourceDocumentIds: ["src_zunaira", "src_maria"],
    decision: "approve_standard",
    status: "resolved",
    createdAt,
  },
];
